service: dofus-bubble

package:
  individually: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    ACCOUNT: '166257563783'
    AWS_UTILS: 2
    PRICES_TABLE: '${self:service.}-prices'
    FAMILIER_TABLE: '${self:service.}-familier'

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PRICE_TABLE}"
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.FAMILIER_TABLE}"

functions:
  scan_prices:
    handler: dofus_bubble/price/lambdas.scan
    events:
      - http:
          path: dofus_bubble/prices
          method: get
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

  get_prices:
    handler: dofus_bubble/price/lambdas.get
    events:
      - http:
          path: dofus_bubble/prices/{_id}
          method: get
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

  put_prices:
    handler: dofus_bubble/price/lambdas.put
    events:
      - http:
          path: dofus_bubble/prices
          method: post
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

  scan_items_price:
    handler: dofus_bubble/dofus/lambdas.scan_items_price
    events:
      - http:
          path: dofus_bubble/dofus/{endpoint}
          method: get
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

  scan_familiers_price:
    handler: dofus_bubble/dofus/lambdas.scan_familiers_price
    events:
      - http:
          path: dofus_bubble/dofus/familiers
          method: get
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

  scan_profession_craft:
    handler: dofus_bubble/dofus/lambdas.scan_profession_craft
    events:
      - http:
          path: dofus_bubble/dofus/{profession}
          method: get
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"