service: dofus-bubble

package:
  individually: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    ACCOUNT: '166257563783'
    DYNAMODB_TABLE: ${self:service}
    AWS_UTILS: "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:13"

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  get_all_items:
    handler: dofus_bubble/dynamodb/get_all_items.get_all_items
    events:
      - http:
          path: dofus_bubble/dynamodb
          method: get
          cors: true
    layers:
      - ${self:provider.environment.AWS_UTILS}