service: dofus-bubble

package:
  individually: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    ACCOUNT: '166257563783'
    DYNAMODB_TABLE: ${self:service}
    AWS_UTILS: 39

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  scan_consumables:
    handler: dofus_bubble/dofapi/lambdas.scan_consumables
    events:
      - http:
          path: dofus_bubble/consumables
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_equipments:
    handler: dofus_bubble/dofapi/lambdas.scan_equipments
    events:
      - http:
          path: dofus_bubble/equipments
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_idols:
    handler: dofus_bubble/dofapi/lambdas.scan_idols
    events:
      - http:
          path: dofus_bubble/idols
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_resources:
    handler: dofus_bubble/dofapi/lambdas.scan_resources
    events:
      - http:
          path: dofus_bubble/resources
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_weapons:
    handler: dofus_bubble/dofapi/lambdas.scan_weapons
    events:
      - http:
          path: dofus_bubble/weapons
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  _scan_items:
    handler: dofus_bubble/dofapi/lambdas._scan_items
    events:
      - http:
          path: dofus_bubble
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_items:
    handler: dofus_bubble/dynamodb/lambdas.scan_items
    events:
      - http:
          path: dofus_bubble/dynamodb
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  get_item:
    handler: dofus_bubble/dynamodb/lambdas.get_item
    events:
      - http:
          path: dofus_bubble/dynamodb/{_id}
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  put_item:
    handler: dofus_bubble/dynamodb/lambdas.put_item
    events:
      - http:
          path: dofus_bubble/dynamodb
          method: post
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_items_craft:
    handler: dofus_bubble/dofus/lambdas.scan_items_craft
    events:
      - http:
          path: dofus_bubble/dofus
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_consumables_price:
    handler: dofus_bubble/dofus/lambdas.scan_consumables_price
    events:
      - http:
          path: dofus_bubble/dofus/consumables
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_equipments_price:
    handler: dofus_bubble/dofus/lambdas.scan_equipments_price
    events:
      - http:
          path: dofus_bubble/dofus/equipments
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_idols_price:
    handler: dofus_bubble/dofus/lambdas.scan_idols_price
    events:
      - http:
          path: dofus_bubble/dofus/idols
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_resources_price:
    handler: dofus_bubble/dofus/lambdas.scan_resources_price
    events:
      - http:
          path: dofus_bubble/dofus/resources
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_weapons_price:
    handler: dofus_bubble/dofus/lambdas.scan_weapons_price
    events:
      - http:
          path: dofus_bubble/dofus/weapons
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"