service: dofus-bubble

package:
  individually: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    ACCOUNT: '166257563783'
    AWS_UTILS: 3
    PRICES_TABLE: '${self:service}-prices'
    FAMILIER_TABLE: '${self:service}-familier'

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PRICES_TABLE}"
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.FAMILIER_TABLE}"

functions:
  put_prices:
    handler: dofus_bubble/price/lambdas.put
    events:
      - http:
          path: dofus_bubble/prices
          method: post
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

  scan_items_price:
    handler: dofus_bubble/dofus/lambdas.scan_items_price
    events:
      - http:
          path: dofus_bubble/dofus/{items}
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

  scan_familiers_price:
    handler: dofus_bubble/dofus/lambdas.scan_familiers_price
    events:
      - http:
          path: dofus_bubble/dofus/familiers
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

  scan_profession_price:
    handler: dofus_bubble/dofus/lambdas.scan_profession_price
    events:
      - http:
          path: dofus_bubble/dofus/professions/{profession}
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils-${self:provider.stage}:${self:provider.environment.AWS_UTILS}"

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'